/*

Enter custom T-SQL here that would run after SQL Server has started up. 

*/
USE [master]
GO

/****** Object:  Database [LegitDB]    Script Date: 19-04-2023 11:34:24 PM ******/
CREATE DATABASE [LegitDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LegitDB', FILENAME = N'/var/opt/mssql/data/LegitDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LegitDB_log', FILENAME = N'/var/opt/mssql/data/LegitDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LegitDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LegitDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LegitDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LegitDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LegitDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LegitDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LegitDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LegitDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LegitDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LegitDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LegitDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LegitDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LegitDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LegitDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LegitDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LegitDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LegitDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LegitDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LegitDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LegitDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LegitDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LegitDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LegitDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LegitDB] SET RECOVERY FULL 
GO

ALTER DATABASE [LegitDB] SET  MULTI_USER 
GO

ALTER DATABASE [LegitDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LegitDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LegitDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LegitDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LegitDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LegitDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LegitDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LegitDB] SET  READ_WRITE 
GO

CREATE LOGIN [areeb] WITH PASSWORD=N'Legit@1234', DEFAULT_DATABASE=[LegitDB], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO
USE [LegitDB]
GO
CREATE USER [areeb] FOR LOGIN [areeb]
GO
USE [LegitDB]
GO
ALTER USER [areeb] WITH DEFAULT_SCHEMA=[dbo]
GO
