FROM mcr.microsoft.com/mssql/server:2019-latest

USER root
# Create a config directory
RUN mkdir -p /usr/config
WORKDIR /usr/config

# Bundle config source
COPY . /usr/config
# Grant permissions for to our scripts to be executable
RUN chmod +x setup.sql

USER mssql

ENTRYPOINT /bin/bash ./entrypoint.sh

